
@host = http://localhost:5026
POST {{host}}/api/Account/Register
Content-Type: application/json

{
    "name": "Admin",
    "phone": "01000",
    "email": "Admin@gmail.com",
    "address": "string",
    "password": "AdminAdmin1!"   
}

