
@host = http://localhost:5026
POST {{host}}/api/Account/Register
Content-Type: application/json

{
    "name": "Khalil",
    "phone": "01000",
    "email": "khalil@example.com",
    "address": "string",
    "password": "Khalil123!"   
}

